version: '2'

services:

  helloprint-db:
    image: mysql:5.6.27
    container_name: helloprint-db
    env_file:
      - ./docker/db_helloprint/dev.env
    ports:
      - 3306:3306
    volumes:
      - ./docker/db_helloprint/mysql:/var/lib/mysql
      - ./docker/db_helloprint/helloprint.sql:/docker-entrypoint-initdb.d/helloprint.sql
    restart: always

  php_website:
    container_name: helloprint-website
    build: docker/php
    volumes:
      - ./Website:/var/www/html
      - /var/log/apache2/helloprint:/var/log/apache2/
    ports:
      - 8000:80

  php_api:
    container_name: helloprint-api
    build: docker/php
    volumes:
      - ./API:/var/www/html
      - /var/log/apache2/helloprintapi:/var/log/apache2/
    ports:
      - '8001:80'
    depends_on:
      - helloprint-db
      - helloprint-core-rabbit
    external_links:
      - helloprint-db
      - helloprint-core-rabbit
    links:
      - helloprint-db
      - helloprint-core-rabbit

  php_core:
    container_name: helloprint-core
    hostname: helloprint-core
    build: docker/php_core
    volumes:
      - ./Core:/var/www/html
      - /var/log/apache2/helloprintcore:/var/log/apache2/
    ports:
      - 8002:80
    depends_on:
      - helloprint-db
      - helloprint-core-rabbit
    external_links:
      - helloprint-db
      - helloprint-core-rabbit
    links:
      - helloprint-db
      - helloprint-core-rabbit

  helloprint-core-rabbit:
    container_name: helloprint-core-rabbit
    image: rabbitmq:3-management
    hostname: helloprint-core-rabbit
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - 15672:15672
      - 5672:5672
    labels:
      NAME: rabbitmq1
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
    depends_on:
      - php_website
