version: '2'

services:
  php:
    build: docker/php
    volumes:
      - ./:/var/www/html
      - /var/log/apache2/helloprint:/var/log/apache2/
    ports:
      - '8000:80'
    env_file:
      - dev.env
    depends_on:
      - db_helloprint


  db_helloprint:
    build: ./docker/db_helloprint